### ISSUE TITLE
Fails to compile - float equality issue

### ISSUE THREAD

**Issue by freevryheid** [certik/fortran-utils#16]
[grassy@rockarch fortran-utils]$ f95 -v
Using built-in specs.
COLLECT_GCC=f95
COLLECT_LTO_WRAPPER=/usr/lib/gcc/x86_64-pc-linux-gnu/6.2.1/lto-wrapper
Target: x86_64-pc-linux-gnu
Configured with: /build/gcc/src/gcc/configure --prefix=/usr --libdir=/usr/lib --libexecdir=/usr/lib --mandir=/usr/share/man --infodir=/usr/share/info --with-bugurl=https://bugs.archlinux.org/ --enable-languages=c,c++,ada,fortran,go,lto,objc,obj-c++ --enable-shared --enable-threads=posix --enable-libmpx --with-system-zlib --with-isl --enable-__cxa_atexit --disable-libunwind-exceptions --enable-clocale=gnu --disable-libstdcxx-pch --disable-libssp --enable-gnu-unique-object --enable-linker-build-id --enable-lto --enable-plugin --enable-install-libiberty --with-linker-hash-style=gnu --enable-gnu-indirect-function --disable-multilib --disable-werror --enable-checking=release
Thread model: posix
gcc version 6.2.1 20160830 (GCC) 
[grassy@rockarch fortran-utils]$ cmake .
Configuration results
---------------------
Fortran compiler: /usr/bin/f95
Build type: Debug
Fortran compiler flags: -std=f2008 -Wall -Wextra -Wimplicit-interface -fPIC -Werror -fmax-errors=1 -g -fcheck=all -fbacktrace
Installation prefix: /usr/local
With LAPACK: yes
With HDF5: no
-- Configuring done
-- Generating done
-- Build files have been written to: /home/grassy/ftn/fortran-utils
[grassy@rockarch fortran-utils]$ make
[  1%] Building Fortran object src/CMakeFiles/fortran_utils.dir/types.f90.o
[  2%] Building Fortran object src/CMakeFiles/fortran_utils.dir/utils.f90.o
[  2%] Building Fortran object src/CMakeFiles/fortran_utils.dir/amos.f90.o
[  2%] Building Fortran object src/CMakeFiles/fortran_utils.dir/constants.f90.o
[  3%] Building Fortran object src/CMakeFiles/fortran_utils.dir/optimize.f90.o
/home/grassy/ftn/fortran-utils/src/optimize.f90:35:8:
     if (fc == 0) return   ! We need to make sure f(c) is not zero below
        1
Error: Equality comparison for REAL(8) at (1) [-Werror]
compilation terminated due to -fmax-errors=1.
f951: all warnings being treated as errors
make[3]: *** [src/CMakeFiles/fortran_utils.dir/build.make:207: src/CMakeFiles/fortran_utils.dir/optimize.f90.o] Error 1
make[2]: *** [src/CMakeFiles/fortran_utils.dir/build.make:222: src/CMakeFiles/fortran_utils.dir/optimize.f90.o.provides] Error 2
make[1]: *** [CMakeFiles/Makefile2:88: src/CMakeFiles/fortran_utils.dir/all] Error 2
make: *** [Makefile:95: all] Error 2

**Comment by certik** [comment]
Thanks for the report. We have to update the code to use the abs(a-b) <
tiny(1._dp) idiom.

**Comment by freevryheid** [comment]
Perhaps relax these compiler flags:
-Werror -fmax-errors=1

picking up warnings in other functions as well.

**Comment by certik** [comment]
Yes, that should be done as well.

**Comment by krvajalmiguelangel** [comment]
@certik  can we close this issue?

**Comment by certik** [comment]
@krvajalmiguelangel yes, we can. Thanks!
