### ISSUE TITLE
Fails to compile: Obsolescent feature: DO termination statement which is not END DO

### ISSUE THREAD

**Issue by krvajal** [certik/fortran-utils#19]
When compiling the current version I get the following error

``` bash
[  1%] Building Fortran object src/CMakeFiles/fortran_utils.dir/optimize.f90.o
[  2%] Building Fortran object src/CMakeFiles/fortran_utils.dir/lapack.f90.o
[  3%] Building Fortran object src/CMakeFiles/fortran_utils.dir/linalg.f90.o
[  3%] Building Fortran object src/CMakeFiles/fortran_utils.dir/mesh.f90.o
[  4%] Building Fortran object src/CMakeFiles/fortran_utils.dir/ppm.f90.o
[  5%] Building Fortran object src/CMakeFiles/fortran_utils.dir/sorting.f90.o
[  6%] Building Fortran object src/CMakeFiles/fortran_utils.dir/special.f90.o
/Users/carvajal/fortran-utils/src/special.f90:565:25:

 10            DJ(K)=0.0D0
                         1
Error: Obsolescent feature: DO termination statement which is not END DO or CONTINUE with label 10 at (1) [-Werror]
```

**Comment by certik** [comment]
Thanks. I think I should put those special functions into a special `.f` file and compile that file with legacy Fortran.

**Comment by krvajalmiguelangel** [comment]
Do you mean to change the special.f90 to special.f or move the functions inside to a separate file?

**Comment by certik** [comment]
Just move the F77 functions that I took from SciPy to a separate file. I thought you can compile them as part of a modern Fortran code, but this error shows that really you can't.

**Comment by krvajalmiguelangel** [comment]
@certik  shall I do that and send a pull request?

**Comment by certik** [comment]
@krvajalmiguelangel that would be great. I am busy today to do it myself.

**Comment by jacobwilliams** [comment]
All you need is to add some `end do`'s like so:
```fortran
           DO K=0,N
              SJ(K)=0.0D0
              DJ(K)=0.0D0
           END DO
```

**Comment by krvajal** [comment]
@jacobwilliams I already sent a pull request and it got fixed. Shall I close the issue @certik ?

**Comment by certik** [comment]
@krvajal that would be great. And indicate which PR fixed it.

**Comment by krvajal** [comment]
@certik turns out that just moving the source code to a separate file with the `.f` extensions do not fix the issue because the same flags are been used for all Fortran files, this flag is `-std=f2008` and makes the warnings to appear. 
One possible solution is to fix the *DO LOOPS* by removing the tag and adopting the new style or moving the files with the `.f` extension to a separate directory and use the `-std=legacy` option when compiling them.
Please let me know which direction you like the most.

**Comment by certik** [comment]
@krvajal in other projects I simply fix this in cmake to compile F77, e.g.: https://github.com/certik/minpack/blob/b3ea6c29debe689a20cb6884cce9b09dce6d0a00/src/CMakeLists.txt, and one can do that on a per file basis as well.

**Comment by nsgates** [comment]
I am getting the exact same error as above. Did a fix for this get implemented? I pulled the latest version of fortran-utils just yesterday. 

```
[  2%] Building Fortran object src/CMakeFiles/fortran_utils.dir/types.f90.o
[  4%] Building Fortran object src/CMakeFiles/fortran_utils.dir/utils.f90.o
[  4%] Building Fortran object src/CMakeFiles/fortran_utils.dir/amos.f90.o
[  4%] Building Fortran object src/CMakeFiles/fortran_utils.dir/constants.f90.o
[  7%] Building Fortran object src/CMakeFiles/fortran_utils.dir/optimize.f90.o
[  9%] Building Fortran object src/CMakeFiles/fortran_utils.dir/lapack.f90.o
[ 12%] Building Fortran object src/CMakeFiles/fortran_utils.dir/linalg.f90.o
[ 12%] Building Fortran object src/CMakeFiles/fortran_utils.dir/mesh.f90.o
[ 14%] Building Fortran object src/CMakeFiles/fortran_utils.dir/ppm.f90.o
[ 17%] Building Fortran object src/CMakeFiles/fortran_utils.dir/sorting.f90.o
[ 19%] Building Fortran object src/CMakeFiles/fortran_utils.dir/special.f90.o
/Users/nsgates/Documents/fortran-utils/src/special.f90:565:25:

 10            DJ(K)=0.0D0
                         1
Error: Obsolescent feature: DO termination statement which is not END DO or CONTINUE with label 10 at (1) [-Werror]
```

**Comment by certik** [comment]
@krvajal, @nsgates things should be fixed now. If anything does not work, let me know.

**Comment by 8vTv8** [comment]
> @certik turns out that just moving the source code to a separate file with the `.f` extensions do not fix the issue because the same flags are been used for all Fortran files, this flag is `-std=f2008` and makes the warnings to appear. One possible solution is to fix the _DO LOOPS_ by removing the tag and adopting the new style or moving the files with the `.f` extension to a separate directory and use the `-std=legacy` option when compiling them. Please let me know which direction you like the most.

how do you use the '-std=legacy' option when compiling? Sorry, I am a beginner. Thanks
